#!/usr/bin/env python3
"""
Generate polaris/neosom input configuration from quasar ELFs.

This script takes ELFs generated by tt-metal JIT for quasar and creates
the inputcfg.json file needed by polaris/ttsim simulator.

Usage:
    python generate_polaris_config.py <elf_directory> [--activation gelu] [--config p1_s4]
"""

import argparse
import json
import os
from pathlib import Path


def find_elf_files(elf_dir: Path) -> dict:
    """Find and categorize ELF files in the directory."""
    elfs = {
        "brisc": None,
        "ncrisc": None,
        "trisc0": None,
        "trisc1": None,
        "trisc2": None,
    }

    for elf_file in elf_dir.glob("*.elf"):
        name = elf_file.stem.lower()

        if "brisc" in name:
            elfs["brisc"] = elf_file
        elif "ncrisc" in name:
            elfs["ncrisc"] = elf_file
        elif "trisc0" in name or "unpack" in name:
            elfs["trisc0"] = elf_file
        elif "trisc1" in name or "math" in name:
            elfs["trisc1"] = elf_file
        elif "trisc2" in name or "pack" in name:
            elfs["trisc2"] = elf_file

    return elfs


def generate_inputcfg(
    elf_dir: Path,
    output_path: Path,
    activation: str = "gelu",
    config: str = "p1_s4",
    description: str = None,
) -> dict:
    """Generate polaris inputcfg.json from ELF files."""

    elfs = find_elf_files(elf_dir)

    # Count available threads
    num_threads = sum(1 for v in elfs.values() if v is not None)

    # Build thread configuration
    thread_config = {}
    thread_idx = 0

    for core_name, elf_path in elfs.items():
        if elf_path is not None:
            thread_config[f"th{thread_idx}Elf"] = elf_path.name
            thread_config[f"th{thread_idx}Path"] = str(elf_dir.absolute())
            thread_idx += 1

    # Parse config string (e.g., "p1_s4" -> degree=1, segments=4)
    degree = 1
    segments = 4
    if config:
        parts = config.lower().replace("p", "").replace("s", "_").split("_")
        if len(parts) >= 2:
            try:
                degree = int(parts[0])
                segments = int(parts[1])
            except ValueError:
                pass

    inputcfg = {
        "arch": "ttqs",
        "llkVersionTag": "sep23",
        "debug": 15,
        "numTCores": 1,
        "input": {
            "syn": 0,
            "name": f"{activation}-{config}-lut-activation",
            "tc0": {
                "numThreads": num_threads,
                "startFunction": "main",
                **thread_config,
            },
        },
        "description": {
            "kernel": config,
            "activation": activation,
            "degree": degree,
            "segments": segments,
            "source": "tt-metal generic_lut_activation (quasar ttsim)",
            "note": description or f"Generated from {elf_dir}",
        },
    }

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(inputcfg, f, indent=2)

    return inputcfg


def main():
    parser = argparse.ArgumentParser(
        description="Generate polaris inputcfg.json from quasar ELFs"
    )
    parser.add_argument("elf_dir", type=Path, help="Directory containing ELF files")
    parser.add_argument(
        "--activation", "-a", default="gelu", help="Activation function name"
    )
    parser.add_argument(
        "--config", "-c", default="p1_s4", help="Configuration (e.g., p1_s4)"
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=None,
        help="Output path for inputcfg.json",
    )
    parser.add_argument("--description", "-d", help="Optional description")

    args = parser.parse_args()

    if not args.elf_dir.is_dir():
        print(f"ERROR: {args.elf_dir} is not a directory")
        return 1

    # Default output path
    if args.output is None:
        args.output = args.elf_dir / "inputcfg.json"

    print(f"ELF directory: {args.elf_dir}")
    print(f"Activation: {args.activation}")
    print(f"Config: {args.config}")
    print(f"Output: {args.output}")
    print()

    # Find ELFs
    elfs = find_elf_files(args.elf_dir)
    print("Found ELFs:")
    for core, path in elfs.items():
        status = path.name if path else "(not found)"
        print(f"  {core}: {status}")
    print()

    # Generate config
    config = generate_inputcfg(
        args.elf_dir,
        args.output,
        activation=args.activation,
        config=args.config,
        description=args.description,
    )

    print("Generated inputcfg.json:")
    print(json.dumps(config, indent=2))
    print()
    print(f"Saved to: {args.output}")

    # Print polaris run command
    print()
    print("To run with polaris:")
    print(f"  cd /localdev/nkapre/polaris")
    print(f"  python ttsim/back/tensix_neo/tneoSim.py {args.output}")

    return 0


if __name__ == "__main__":
    exit(main())
