// Auto-generated adhoc rational configuration header
// Generated by sweep_best.sh - DO NOT EDIT MANUALLY.
#pragma once
#define ADHOC_NUM_DEGREE 7
#define ADHOC_DEN_DEGREE 6
#define ADHOC_NUM_SEGMENTS 1
#define ADHOC_LUT_SIZE 17
