#!/bin/bash
# Automated server reservation orchestrator
# Reserves 2 Wormhole and 3 Blackhole machines

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default values
ARCH="both"
WORMHOLE_MODEL="x1"
WORMHOLE_COUNT="4"
BLACKHOLE_MODEL="p100"
BLACKHOLE_COUNT="3"
TIMEOUT="10:00:00"

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --arch) ARCH="$2"; shift 2 ;;
        --wormhole-model) WORMHOLE_MODEL="$2"; shift 2 ;;
        --wormhole-count) WORMHOLE_COUNT="$2"; shift 2 ;;
        --blackhole-model) BLACKHOLE_MODEL="$2"; shift 2 ;;
        --blackhole-count) BLACKHOLE_COUNT="$2"; shift 2 ;;
        --timeout) TIMEOUT="$2"; shift 2 ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--arch wormhole_b0|blackhole|both] [--wormhole-model x1|x2] [--wormhole-count 1|2] [--blackhole-model p100|p150] [--blackhole-count 1|2|3] [--timeout HH:MM:SS]"
            exit 1
            ;;
    esac
done

# Validate arguments
[[ "$ARCH" =~ ^(wormhole_b0|blackhole|both)$ ]] || { echo "Error: --arch must be wormhole_b0, blackhole, or both"; exit 1; }
[[ "$WORMHOLE_MODEL" =~ ^(x1|x2)$ ]] || { echo "Error: --wormhole-model must be x1 or x2"; exit 1; }
[[ "$WORMHOLE_COUNT" =~ ^(1|2|3|4)$ ]] || { echo "Error: --wormhole-count must be 1 or 2"; exit 1; }
[[ "$BLACKHOLE_MODEL" =~ ^(p100|p150)$ ]] || { echo "Error: --blackhole-model must be p100 or p150"; exit 1; }
[[ "$BLACKHOLE_COUNT" =~ ^(1|2|3|4|5)$ ]] || { echo "Error: --blackhole-count must be 1, 2, 3, or 4"; exit 1; }

echo "=========================================="
echo "Automated Server Reservation"
echo "=========================================="
echo "Architecture: $ARCH"
[[ "$ARCH" =~ wormhole ]] && echo "Wormhole model: $WORMHOLE_MODEL, count: $WORMHOLE_COUNT"
[[ "$ARCH" =~ blackhole ]] && echo "Blackhole model: $BLACKHOLE_MODEL, count: $BLACKHOLE_COUNT"
echo "Timeout: $TIMEOUT"
echo ""

# Functions

validate_reservation() {
    local host=$1 port=$2
    MATCH=$(echo "$IRD_LIST" | grep "$host" | grep "$port" || true)
    [[ -n "$MATCH" ]]
}

clean_ssh_key() {
    local host=$1 port=$2
    echo "Removing stale SSH key for $host:$port"
    ssh-keygen -R "[$host]:$port" 2>/dev/null || true
}

scan_for_reservation() {
    local arch=$1  # "wormhole" or "blackhole"

    set +e
    while IFS= read -r line; do
        [[ "$line" =~ ^[[:space:]]*$ ]] && continue
        [[ "$line" =~ SELECTION|INFO ]] && continue

        MACHINE=$(echo "$line" | awk '{print $5}')
        JOB_ID=$(echo "$line" | awk '{print $10}')
        PORT=$(echo "$line" | awk '{print $11}')

        [[ -z "$MACHINE" || -z "$JOB_ID" || -z "$PORT" ]] && continue

        # Check if already assigned
        local already_assigned=false
        for slot in "$WORMHOLE1_HOST:$WORMHOLE1_PORT" "$WORMHOLE2_HOST:$WORMHOLE2_PORT" "$BLACKHOLE1_HOST:$BLACKHOLE1_PORT" "$BLACKHOLE2_HOST:$BLACKHOLE2_PORT" "$BLACKHOLE3_HOST:$BLACKHOLE3_PORT" "$BLACKHOLE4_HOST:$BLACKHOLE4_PORT"; do
            [[ "$slot" == "$MACHINE:$PORT" ]] && already_assigned=true && break
        done
        $already_assigned && continue

        # Check architecture match
        if [[ "$arch" == "wormhole" ]]; then
            [[ "$MACHINE" =~ (wormhole|wh-|yyzc-wh-|tt-) ]] || continue
        else
            [[ "$MACHINE" =~ (blackhole|bh-|yyzo-bh-|nebula-) ]] || continue
        fi

        echo "$MACHINE:$PORT:$JOB_ID"
        return 0
    done <<< "$IRD_LIST"
    set -e
    return 1
}

reserve_new_machine() {
    local arch=$1 model=$2 timeout=$3

    OUTPUT=$(ssh yyz-ird "ird reserve --timeout $timeout $arch --model $model" 2>&1)
    HOST=$(echo "$OUTPUT" | grep "assigned" | sed -E 's/.*assigned ([a-z0-9-]+).*/\1/' | head -1)
    PORT=$(echo "$OUTPUT" | grep "SSH with" | sed -E 's/.*-p ([0-9]+).*/\1/' | head -1)

    [[ -z "$HOST" || -z "$PORT" ]] && echo "❌ Failed to parse reservation" && return 1

    JOB_ID=$(ssh yyz-ird 'ird list' 2>&1 | grep "$HOST" | grep "$PORT" | awk '{print $10}' | head -1)
    ssh-keygen -R "[$HOST]:$PORT" 2>/dev/null || true

    if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -A "$HOST" -p "$PORT" 'echo "SSH OK"' 2>/dev/null | grep -q "SSH OK"; then
        echo "✓ Reserved: $HOST:$PORT (Job ID: $JOB_ID)"
    else
        echo "⚠️  Reserved $HOST:$PORT but SSH verification failed"
    fi

    echo "$HOST:$PORT:$JOB_ID"
}

update_timeout() {
    local job_id=$1 timeout=$2
    ssh yyz-ird "ird change-timeout $job_id $timeout" 2>&1 | grep -q "successfully" || echo "⚠️  Failed to update timeout"
}

write_hosts_file() {
    cat > "$SCRIPT_DIR/hosts.sh" << 'EOF'
#!/bin/bash
# Server configuration for remote benchmarks
# Auto-generated by auto_reserve.sh

MODEL_TYPES=("default")

EOF

    # Write Wormhole configs
    if [[ -n "$WORMHOLE1_HOST" ]]; then
        cat >> "$SCRIPT_DIR/hosts.sh" << EOF
# Wormhole B0 server #1 ($WORMHOLE_MODEL)
WORMHOLE1_HOST="$WORMHOLE1_HOST"
WORMHOLE1_PORT="$WORMHOLE1_PORT"
WORMHOLE1_PASSWORD="$WORMHOLE1_PASSWORD"
WORMHOLE1_JOB_ID="$WORMHOLE1_JOB_ID"

EOF
    fi

    if [[ -n "$WORMHOLE2_HOST" ]]; then
        cat >> "$SCRIPT_DIR/hosts.sh" << EOF
# Wormhole B0 server #2 ($WORMHOLE_MODEL)
WORMHOLE2_HOST="$WORMHOLE2_HOST"
WORMHOLE2_PORT="$WORMHOLE2_PORT"
WORMHOLE2_PASSWORD="$WORMHOLE2_PASSWORD"
WORMHOLE2_JOB_ID="$WORMHOLE2_JOB_ID"

EOF
    fi

    if [[ -n "$WORMHOLE1_HOST" ]]; then
        cat >> "$SCRIPT_DIR/hosts.sh" << EOF
# Backward compatibility (uses Wormhole1)
WORMHOLE_DEFAULT_HOST="$WORMHOLE1_HOST"
WORMHOLE_DEFAULT_PORT="$WORMHOLE1_PORT"
WORMHOLE_HOST="$WORMHOLE1_HOST"
WORMHOLE_PORT="$WORMHOLE1_PORT"
WORMHOLE_PASSWORD="$WORMHOLE1_PASSWORD"
WORMHOLE_JOB_ID="$WORMHOLE1_JOB_ID"

EOF
    fi

    # Write Blackhole configs
    if [[ -n "$BLACKHOLE1_HOST" ]]; then
        cat >> "$SCRIPT_DIR/hosts.sh" << EOF
# Blackhole server #1 ($BLACKHOLE_MODEL)
BLACKHOLE1_HOST="$BLACKHOLE1_HOST"
BLACKHOLE1_PORT="$BLACKHOLE1_PORT"
BLACKHOLE1_PASSWORD="$BLACKHOLE1_PASSWORD"
BLACKHOLE1_JOB_ID="$BLACKHOLE1_JOB_ID"

EOF
    fi

    if [[ -n "$BLACKHOLE2_HOST" ]]; then
        cat >> "$SCRIPT_DIR/hosts.sh" << EOF
# Blackhole server #2 ($BLACKHOLE_MODEL)
BLACKHOLE2_HOST="$BLACKHOLE2_HOST"
BLACKHOLE2_PORT="$BLACKHOLE2_PORT"
BLACKHOLE2_PASSWORD="$BLACKHOLE2_PASSWORD"
BLACKHOLE2_JOB_ID="$BLACKHOLE2_JOB_ID"

EOF
    fi

    if [[ -n "$BLACKHOLE3_HOST" ]]; then
        cat >> "$SCRIPT_DIR/hosts.sh" << EOF
# Blackhole server #3 ($BLACKHOLE_MODEL)
BLACKHOLE3_HOST="$BLACKHOLE3_HOST"
BLACKHOLE3_PORT="$BLACKHOLE3_PORT"
BLACKHOLE3_PASSWORD="$BLACKHOLE3_PASSWORD"
BLACKHOLE3_JOB_ID="$BLACKHOLE3_JOB_ID"

EOF
    fi

    if [[ -n "$BLACKHOLE4_HOST" ]]; then
        cat >> "$SCRIPT_DIR/hosts.sh" << EOF
# Blackhole server #4 ($BLACKHOLE_MODEL)
BLACKHOLE4_HOST="$BLACKHOLE4_HOST"
BLACKHOLE4_PORT="$BLACKHOLE4_PORT"
BLACKHOLE4_PASSWORD="$BLACKHOLE4_PASSWORD"
BLACKHOLE4_JOB_ID="$BLACKHOLE4_JOB_ID"

EOF
    fi

    if [[ -n "$BLACKHOLE1_HOST" ]]; then
        cat >> "$SCRIPT_DIR/hosts.sh" << EOF
# Backward compatibility (uses Blackhole1)
BLACKHOLE_DEFAULT_HOST="$BLACKHOLE1_HOST"
BLACKHOLE_DEFAULT_PORT="$BLACKHOLE1_PORT"
BLACKHOLE_HOST="$BLACKHOLE1_HOST"
BLACKHOLE_PORT="$BLACKHOLE1_PORT"
BLACKHOLE_PASSWORD="$BLACKHOLE1_PASSWORD"
BLACKHOLE_JOB_ID="$BLACKHOLE1_JOB_ID"

EOF
    fi

    cat >> "$SCRIPT_DIR/hosts.sh" << 'EOF'
# Remote working directory (same on all servers)
REMOTE_DIR="localdev/nkapre/tt-metal"
EOF

    echo "✓ Generated $SCRIPT_DIR/hosts.sh"
}

# Main execution

echo "Checking for existing reservations..."
echo "-------------------------------------------"
IRD_LIST=$(ssh yyz-ird 'ird list' 2>&1)

# Load existing config
if [[ -f "$SCRIPT_DIR/hosts.sh" ]]; then
    echo "Found existing hosts.sh, validating..."
    source "$SCRIPT_DIR/hosts.sh" 2>/dev/null || true

    # Validate and clean stale entries
    for var in WORMHOLE1 WORMHOLE2 BLACKHOLE1 BLACKHOLE2 BLACKHOLE3 BLACKHOLE4; do
        eval "HOST=\${${var}_HOST}"
        eval "PORT=\${${var}_PORT}"
        eval "JOB=\${${var}_JOB_ID}"

        if [[ -n "$HOST" && -n "$PORT" ]]; then
            if validate_reservation "$HOST" "$PORT"; then
                echo "✓ Existing $var: $HOST:$PORT (Job: $JOB)"
                eval "${var}_VALID=true"
            else
                echo "⚠️  $var host $HOST:$PORT is no longer reserved (clearing)"
                clean_ssh_key "$HOST" "$PORT"
                eval "unset ${var}_HOST ${var}_PORT ${var}_PASSWORD ${var}_JOB_ID"
                eval "${var}_VALID=false"
            fi
        else
            eval "${var}_VALID=false"
        fi
    done
fi
echo ""

# Scan for additional reservations
echo "Scanning for other active reservations..."
echo "-------------------------------------------"

if [[ "$ARCH" == "both" || "$ARCH" == "wormhole_b0" ]]; then
    for i in $(seq 1 $WORMHOLE_COUNT); do
        eval "valid=\${WORMHOLE${i}_VALID:-false}"
        if [[ "$valid" == "false" ]]; then
            if result=$(scan_for_reservation "wormhole"); then
                IFS=: read -r host port job <<< "$result"
                eval "WORMHOLE${i}_HOST='$host'"
                eval "WORMHOLE${i}_PORT='$port'"
                eval "WORMHOLE${i}_PASSWORD=''"
                eval "WORMHOLE${i}_JOB_ID='$job'"
                echo "✓ Found existing Wormhole reservation: $host:$port (Job: $job)"
            fi
        fi
    done
fi

if [[ "$ARCH" == "both" || "$ARCH" == "blackhole" ]]; then
    for i in $(seq 1 $BLACKHOLE_COUNT); do
        eval "valid=\${BLACKHOLE${i}_VALID:-false}"
        if [[ "$valid" == "false" ]]; then
            if result=$(scan_for_reservation "blackhole"); then
                IFS=: read -r host port job <<< "$result"
                eval "BLACKHOLE${i}_HOST='$host'"
                eval "BLACKHOLE${i}_PORT='$port'"
                eval "BLACKHOLE${i}_PASSWORD=''"
                eval "BLACKHOLE${i}_JOB_ID='$job'"
                echo "✓ Found existing Blackhole reservation: $host:$port (Job: $job)"
            fi
        fi
    done
fi
echo ""

# Reserve missing machines
if [[ "$ARCH" == "both" || "$ARCH" == "wormhole_b0" ]]; then
    for i in $(seq 1 $WORMHOLE_COUNT); do
        eval "host=\${WORMHOLE${i}_HOST}"

        if [[ -n "$host" ]]; then
            eval "job=\${WORMHOLE${i}_JOB_ID}"
            echo "Step: Wormhole #$i already reserved ($host)"
            update_timeout "$job" "$TIMEOUT"
        else
            echo "Step: Reserving Wormhole B0 #$i (model: $WORMHOLE_MODEL)..."
            if result=$(reserve_new_machine "wormhole_b0" "$WORMHOLE_MODEL" "$TIMEOUT"); then
                IFS=: read -r host port job <<< "$result"
                eval "WORMHOLE${i}_HOST='$host'"
                eval "WORMHOLE${i}_PORT='$port'"
                eval "WORMHOLE${i}_PASSWORD=''"
                eval "WORMHOLE${i}_JOB_ID='$job'"
            fi
        fi
        echo ""
    done
fi

if [[ "$ARCH" == "both" || "$ARCH" == "blackhole" ]]; then
    for i in $(seq 1 $BLACKHOLE_COUNT); do
        eval "host=\${BLACKHOLE${i}_HOST}"

        if [[ -n "$host" ]]; then
            eval "job=\${BLACKHOLE${i}_JOB_ID}"
            echo "Step: Blackhole #$i already reserved ($host)"
            update_timeout "$job" "$TIMEOUT"
        else
            echo "Step: Reserving Blackhole #$i (model: $BLACKHOLE_MODEL)..."
            if result=$(reserve_new_machine "blackhole" "$BLACKHOLE_MODEL" "$TIMEOUT"); then
                IFS=: read -r host port job <<< "$result"
                eval "BLACKHOLE${i}_HOST='$host'"
                eval "BLACKHOLE${i}_PORT='$port'"
                eval "BLACKHOLE${i}_PASSWORD=''"
                eval "BLACKHOLE${i}_JOB_ID='$job'"
            fi
        fi
        echo ""
    done
fi

# Generate hosts.sh
echo "Generating hosts.sh..."
echo "-------------------------------------------"
write_hosts_file
echo ""

# Summary
echo "=========================================="
echo "✓ All Operations Complete!"
echo "=========================================="
echo ""
echo "Reservation Summary:"
echo "-------------------------------------------"
for i in $(seq 1 $WORMHOLE_COUNT); do
    eval "host=\${WORMHOLE${i}_HOST}"
    eval "port=\${WORMHOLE${i}_PORT}"
    eval "job=\${WORMHOLE${i}_JOB_ID}"
    [[ -n "$host" ]] && echo "Wormhole B0 #$i ($WORMHOLE_MODEL): $host:$port (Job: $job)"
done
for i in $(seq 1 $BLACKHOLE_COUNT); do
    eval "host=\${BLACKHOLE${i}_HOST}"
    eval "port=\${BLACKHOLE${i}_PORT}"
    eval "job=\${BLACKHOLE${i}_JOB_ID}"
    [[ -n "$host" ]] && echo "Blackhole #$i ($BLACKHOLE_MODEL): $host:$port (Job: $job)"
done
echo ""

echo "Active Reservations:"
echo "-------------------------------------------"
ssh yyz-ird 'ird list'
