// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

// AUTO-GENERATED - DO NOT EDIT BY HAND
// Generated by generate_optv2_specialized.py

#pragma once


// Specialization for 4 segments with OptV2 staggered batching
template <uint32_t POLY_DEGREE, uint32_t LUT_SIZE>
inline void piecewise_generic_lut_opt_v2_specialized_4(const std::array<float, LUT_SIZE>& lut) {
    constexpr uint32_t NUM_SEGMENTS = 4;
    constexpr uint32_t COEFFS_PER_SEGMENT = POLY_DEGREE + 1;
    constexpr uint32_t COEFF_OFFSET = NUM_SEGMENTS + 1;
    constexpr uint32_t BATCH_SIZE = 3;

    for (int d = 0; d < 32; d++) {
        vFloat x = dst_reg[d];

        // Clamp x to valid range
        vFloat x_clamped = x;
        v_if (x < lut[0]) {
            x_clamped = lut[0];
        }
        v_endif;
        v_if (x > lut[NUM_SEGMENTS]) {
            x_clamped = lut[NUM_SEGMENTS];
        }
        v_endif;

        vFloat result;

        if constexpr (POLY_DEGREE == 0) {
            // Constant: just load c0 with manual unrolling
            result = lut[COEFF_OFFSET];
            v_if (x_clamped >= lut[1]) { result = lut[COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[2]) { result = lut[COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[3]) { result = lut[COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT]; } v_endif;
        } else {
            // Batch 1: Load highest-degree coefficients
            constexpr uint32_t batch1_size = (POLY_DEGREE >= BATCH_SIZE) ? BATCH_SIZE : POLY_DEGREE;
            constexpr uint32_t batch1_start = POLY_DEGREE + 1 - batch1_size;

            vFloat c[BATCH_SIZE];
            
            // Manual unrolling for batch 1 coefficient loading
            const uint32_t base0 = COEFF_OFFSET;
            if constexpr (batch1_size >= 1) c[0] = lut[base0 + batch1_start];
            if constexpr (batch1_size >= 2) c[1] = lut[base0 + batch1_start + 1];
            if constexpr (batch1_size >= 3) c[2] = lut[base0 + batch1_start + 2];
            v_if (x_clamped >= lut[1]) {
                const uint32_t base1 = COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base1 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base1 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base1 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[2]) {
                const uint32_t base2 = COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base2 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base2 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base2 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[3]) {
                const uint32_t base3 = COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base3 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base3 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base3 + batch1_start + 2];
            }
            v_endif;

            // Evaluate batch 1
            if constexpr (batch1_size == 1) {
                result = c[0];
            } else if constexpr (batch1_size == 2) {
                result = c[1] * x + c[0];
            } else {
                result = (c[2] * x + c[1]) * x + c[0];
            }

            // Process remaining coefficients in additional batches
            if constexpr (POLY_DEGREE >= BATCH_SIZE) {
                constexpr uint32_t remaining_after_b1 = batch1_start;

                // Batch 2
                if constexpr (remaining_after_b1 > 0) {
                    constexpr uint32_t b2_size = (remaining_after_b1 >= BATCH_SIZE) ? BATCH_SIZE : remaining_after_b1;
                    constexpr uint32_t b2_start = remaining_after_b1 - b2_size;

                    if constexpr (b2_size >= 1) c[0] = lut[base0 + b2_start];
                    if constexpr (b2_size >= 2) c[1] = lut[base0 + b2_start + 1];
                    if constexpr (b2_size >= 3) c[2] = lut[base0 + b2_start + 2];
                    v_if (x_clamped >= lut[1]) {
                        const uint32_t base1 = COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base1 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base1 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base1 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[2]) {
                        const uint32_t base2 = COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base2 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base2 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base2 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[3]) {
                        const uint32_t base3 = COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base3 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base3 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base3 + b2_start + 2];
                    }
                    v_endif;

                    if constexpr (b2_size == 1) {
                        result = result * x + c[0];
                    } else if constexpr (b2_size == 2) {
                        result = (result * x + c[1]) * x + c[0];
                    } else {
                        result = ((result * x + c[2]) * x + c[1]) * x + c[0];
                    }
                }

                // Batch 3
                constexpr uint32_t remaining_after_b2 = (remaining_after_b1 > BATCH_SIZE) ? (remaining_after_b1 - BATCH_SIZE) : 0;
                if constexpr (remaining_after_b2 > 0) {
                    constexpr uint32_t b3_size = (remaining_after_b2 >= BATCH_SIZE) ? BATCH_SIZE : remaining_after_b2;
                    constexpr uint32_t b3_start = remaining_after_b2 - b3_size;

                    if constexpr (b3_size >= 1) c[0] = lut[base0 + b3_start];
                    if constexpr (b3_size >= 2) c[1] = lut[base0 + b3_start + 1];
                    if constexpr (b3_size >= 3) c[2] = lut[base0 + b3_start + 2];
                    v_if (x_clamped >= lut[1]) {
                        const uint32_t base1 = COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base1 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base1 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base1 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[2]) {
                        const uint32_t base2 = COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base2 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base2 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base2 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[3]) {
                        const uint32_t base3 = COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base3 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base3 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base3 + b3_start + 2];
                    }
                    v_endif;

                    if constexpr (b3_size == 1) {
                        result = result * x + c[0];
                    } else if constexpr (b3_size == 2) {
                        result = (result * x + c[1]) * x + c[0];
                    } else {
                        result = ((result * x + c[2]) * x + c[1]) * x + c[0];
                    }
                }
            }
        }

        dst_reg[d] = result;
    }
}


// Specialization for 8 segments with OptV2 staggered batching
template <uint32_t POLY_DEGREE, uint32_t LUT_SIZE>
inline void piecewise_generic_lut_opt_v2_specialized_8(const std::array<float, LUT_SIZE>& lut) {
    constexpr uint32_t NUM_SEGMENTS = 8;
    constexpr uint32_t COEFFS_PER_SEGMENT = POLY_DEGREE + 1;
    constexpr uint32_t COEFF_OFFSET = NUM_SEGMENTS + 1;
    constexpr uint32_t BATCH_SIZE = 3;

    for (int d = 0; d < 32; d++) {
        vFloat x = dst_reg[d];

        // Clamp x to valid range
        vFloat x_clamped = x;
        v_if (x < lut[0]) {
            x_clamped = lut[0];
        }
        v_endif;
        v_if (x > lut[NUM_SEGMENTS]) {
            x_clamped = lut[NUM_SEGMENTS];
        }
        v_endif;

        vFloat result;

        if constexpr (POLY_DEGREE == 0) {
            // Constant: just load c0 with manual unrolling
            result = lut[COEFF_OFFSET];
            v_if (x_clamped >= lut[1]) { result = lut[COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[2]) { result = lut[COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[3]) { result = lut[COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[4]) { result = lut[COEFF_OFFSET + 4 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[5]) { result = lut[COEFF_OFFSET + 5 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[6]) { result = lut[COEFF_OFFSET + 6 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[7]) { result = lut[COEFF_OFFSET + 7 * COEFFS_PER_SEGMENT]; } v_endif;
        } else {
            // Batch 1: Load highest-degree coefficients
            constexpr uint32_t batch1_size = (POLY_DEGREE >= BATCH_SIZE) ? BATCH_SIZE : POLY_DEGREE;
            constexpr uint32_t batch1_start = POLY_DEGREE + 1 - batch1_size;

            vFloat c[BATCH_SIZE];
            
            // Manual unrolling for batch 1 coefficient loading
            const uint32_t base0 = COEFF_OFFSET;
            if constexpr (batch1_size >= 1) c[0] = lut[base0 + batch1_start];
            if constexpr (batch1_size >= 2) c[1] = lut[base0 + batch1_start + 1];
            if constexpr (batch1_size >= 3) c[2] = lut[base0 + batch1_start + 2];
            v_if (x_clamped >= lut[1]) {
                const uint32_t base1 = COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base1 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base1 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base1 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[2]) {
                const uint32_t base2 = COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base2 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base2 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base2 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[3]) {
                const uint32_t base3 = COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base3 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base3 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base3 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[4]) {
                const uint32_t base4 = COEFF_OFFSET + 4 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base4 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base4 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base4 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[5]) {
                const uint32_t base5 = COEFF_OFFSET + 5 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base5 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base5 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base5 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[6]) {
                const uint32_t base6 = COEFF_OFFSET + 6 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base6 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base6 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base6 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[7]) {
                const uint32_t base7 = COEFF_OFFSET + 7 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base7 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base7 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base7 + batch1_start + 2];
            }
            v_endif;

            // Evaluate batch 1
            if constexpr (batch1_size == 1) {
                result = c[0];
            } else if constexpr (batch1_size == 2) {
                result = c[1] * x + c[0];
            } else {
                result = (c[2] * x + c[1]) * x + c[0];
            }

            // Process remaining coefficients in additional batches
            if constexpr (POLY_DEGREE >= BATCH_SIZE) {
                constexpr uint32_t remaining_after_b1 = batch1_start;

                // Batch 2
                if constexpr (remaining_after_b1 > 0) {
                    constexpr uint32_t b2_size = (remaining_after_b1 >= BATCH_SIZE) ? BATCH_SIZE : remaining_after_b1;
                    constexpr uint32_t b2_start = remaining_after_b1 - b2_size;

                    if constexpr (b2_size >= 1) c[0] = lut[base0 + b2_start];
                    if constexpr (b2_size >= 2) c[1] = lut[base0 + b2_start + 1];
                    if constexpr (b2_size >= 3) c[2] = lut[base0 + b2_start + 2];
                    v_if (x_clamped >= lut[1]) {
                        const uint32_t base1 = COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base1 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base1 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base1 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[2]) {
                        const uint32_t base2 = COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base2 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base2 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base2 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[3]) {
                        const uint32_t base3 = COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base3 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base3 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base3 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[4]) {
                        const uint32_t base4 = COEFF_OFFSET + 4 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base4 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base4 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base4 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[5]) {
                        const uint32_t base5 = COEFF_OFFSET + 5 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base5 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base5 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base5 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[6]) {
                        const uint32_t base6 = COEFF_OFFSET + 6 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base6 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base6 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base6 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[7]) {
                        const uint32_t base7 = COEFF_OFFSET + 7 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base7 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base7 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base7 + b2_start + 2];
                    }
                    v_endif;

                    if constexpr (b2_size == 1) {
                        result = result * x + c[0];
                    } else if constexpr (b2_size == 2) {
                        result = (result * x + c[1]) * x + c[0];
                    } else {
                        result = ((result * x + c[2]) * x + c[1]) * x + c[0];
                    }
                }

                // Batch 3
                constexpr uint32_t remaining_after_b2 = (remaining_after_b1 > BATCH_SIZE) ? (remaining_after_b1 - BATCH_SIZE) : 0;
                if constexpr (remaining_after_b2 > 0) {
                    constexpr uint32_t b3_size = (remaining_after_b2 >= BATCH_SIZE) ? BATCH_SIZE : remaining_after_b2;
                    constexpr uint32_t b3_start = remaining_after_b2 - b3_size;

                    if constexpr (b3_size >= 1) c[0] = lut[base0 + b3_start];
                    if constexpr (b3_size >= 2) c[1] = lut[base0 + b3_start + 1];
                    if constexpr (b3_size >= 3) c[2] = lut[base0 + b3_start + 2];
                    v_if (x_clamped >= lut[1]) {
                        const uint32_t base1 = COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base1 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base1 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base1 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[2]) {
                        const uint32_t base2 = COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base2 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base2 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base2 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[3]) {
                        const uint32_t base3 = COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base3 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base3 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base3 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[4]) {
                        const uint32_t base4 = COEFF_OFFSET + 4 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base4 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base4 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base4 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[5]) {
                        const uint32_t base5 = COEFF_OFFSET + 5 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base5 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base5 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base5 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[6]) {
                        const uint32_t base6 = COEFF_OFFSET + 6 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base6 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base6 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base6 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[7]) {
                        const uint32_t base7 = COEFF_OFFSET + 7 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base7 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base7 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base7 + b3_start + 2];
                    }
                    v_endif;

                    if constexpr (b3_size == 1) {
                        result = result * x + c[0];
                    } else if constexpr (b3_size == 2) {
                        result = (result * x + c[1]) * x + c[0];
                    } else {
                        result = ((result * x + c[2]) * x + c[1]) * x + c[0];
                    }
                }
            }
        }

        dst_reg[d] = result;
    }
}


// Specialization for 16 segments with OptV2 staggered batching
template <uint32_t POLY_DEGREE, uint32_t LUT_SIZE>
inline void piecewise_generic_lut_opt_v2_specialized_16(const std::array<float, LUT_SIZE>& lut) {
    constexpr uint32_t NUM_SEGMENTS = 16;
    constexpr uint32_t COEFFS_PER_SEGMENT = POLY_DEGREE + 1;
    constexpr uint32_t COEFF_OFFSET = NUM_SEGMENTS + 1;
    constexpr uint32_t BATCH_SIZE = 3;

    for (int d = 0; d < 32; d++) {
        vFloat x = dst_reg[d];

        // Clamp x to valid range
        vFloat x_clamped = x;
        v_if (x < lut[0]) {
            x_clamped = lut[0];
        }
        v_endif;
        v_if (x > lut[NUM_SEGMENTS]) {
            x_clamped = lut[NUM_SEGMENTS];
        }
        v_endif;

        vFloat result;

        if constexpr (POLY_DEGREE == 0) {
            // Constant: just load c0 with manual unrolling
            result = lut[COEFF_OFFSET];
            v_if (x_clamped >= lut[1]) { result = lut[COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[2]) { result = lut[COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[3]) { result = lut[COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[4]) { result = lut[COEFF_OFFSET + 4 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[5]) { result = lut[COEFF_OFFSET + 5 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[6]) { result = lut[COEFF_OFFSET + 6 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[7]) { result = lut[COEFF_OFFSET + 7 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[8]) { result = lut[COEFF_OFFSET + 8 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[9]) { result = lut[COEFF_OFFSET + 9 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[10]) { result = lut[COEFF_OFFSET + 10 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[11]) { result = lut[COEFF_OFFSET + 11 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[12]) { result = lut[COEFF_OFFSET + 12 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[13]) { result = lut[COEFF_OFFSET + 13 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[14]) { result = lut[COEFF_OFFSET + 14 * COEFFS_PER_SEGMENT]; } v_endif;
            v_if (x_clamped >= lut[15]) { result = lut[COEFF_OFFSET + 15 * COEFFS_PER_SEGMENT]; } v_endif;
        } else {
            // Batch 1: Load highest-degree coefficients
            constexpr uint32_t batch1_size = (POLY_DEGREE >= BATCH_SIZE) ? BATCH_SIZE : POLY_DEGREE;
            constexpr uint32_t batch1_start = POLY_DEGREE + 1 - batch1_size;

            vFloat c[BATCH_SIZE];
            
            // Manual unrolling for batch 1 coefficient loading
            const uint32_t base0 = COEFF_OFFSET;
            if constexpr (batch1_size >= 1) c[0] = lut[base0 + batch1_start];
            if constexpr (batch1_size >= 2) c[1] = lut[base0 + batch1_start + 1];
            if constexpr (batch1_size >= 3) c[2] = lut[base0 + batch1_start + 2];
            v_if (x_clamped >= lut[1]) {
                const uint32_t base1 = COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base1 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base1 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base1 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[2]) {
                const uint32_t base2 = COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base2 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base2 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base2 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[3]) {
                const uint32_t base3 = COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base3 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base3 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base3 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[4]) {
                const uint32_t base4 = COEFF_OFFSET + 4 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base4 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base4 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base4 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[5]) {
                const uint32_t base5 = COEFF_OFFSET + 5 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base5 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base5 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base5 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[6]) {
                const uint32_t base6 = COEFF_OFFSET + 6 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base6 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base6 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base6 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[7]) {
                const uint32_t base7 = COEFF_OFFSET + 7 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base7 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base7 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base7 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[8]) {
                const uint32_t base8 = COEFF_OFFSET + 8 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base8 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base8 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base8 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[9]) {
                const uint32_t base9 = COEFF_OFFSET + 9 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base9 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base9 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base9 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[10]) {
                const uint32_t base10 = COEFF_OFFSET + 10 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base10 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base10 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base10 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[11]) {
                const uint32_t base11 = COEFF_OFFSET + 11 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base11 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base11 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base11 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[12]) {
                const uint32_t base12 = COEFF_OFFSET + 12 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base12 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base12 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base12 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[13]) {
                const uint32_t base13 = COEFF_OFFSET + 13 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base13 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base13 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base13 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[14]) {
                const uint32_t base14 = COEFF_OFFSET + 14 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base14 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base14 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base14 + batch1_start + 2];
            }
            v_endif;
            v_if (x_clamped >= lut[15]) {
                const uint32_t base15 = COEFF_OFFSET + 15 * COEFFS_PER_SEGMENT;
                if constexpr (batch1_size >= 1) c[0] = lut[base15 + batch1_start];
                if constexpr (batch1_size >= 2) c[1] = lut[base15 + batch1_start + 1];
                if constexpr (batch1_size >= 3) c[2] = lut[base15 + batch1_start + 2];
            }
            v_endif;

            // Evaluate batch 1
            if constexpr (batch1_size == 1) {
                result = c[0];
            } else if constexpr (batch1_size == 2) {
                result = c[1] * x + c[0];
            } else {
                result = (c[2] * x + c[1]) * x + c[0];
            }

            // Process remaining coefficients in additional batches
            if constexpr (POLY_DEGREE >= BATCH_SIZE) {
                constexpr uint32_t remaining_after_b1 = batch1_start;

                // Batch 2
                if constexpr (remaining_after_b1 > 0) {
                    constexpr uint32_t b2_size = (remaining_after_b1 >= BATCH_SIZE) ? BATCH_SIZE : remaining_after_b1;
                    constexpr uint32_t b2_start = remaining_after_b1 - b2_size;

                    if constexpr (b2_size >= 1) c[0] = lut[base0 + b2_start];
                    if constexpr (b2_size >= 2) c[1] = lut[base0 + b2_start + 1];
                    if constexpr (b2_size >= 3) c[2] = lut[base0 + b2_start + 2];
                    v_if (x_clamped >= lut[1]) {
                        const uint32_t base1 = COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base1 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base1 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base1 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[2]) {
                        const uint32_t base2 = COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base2 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base2 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base2 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[3]) {
                        const uint32_t base3 = COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base3 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base3 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base3 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[4]) {
                        const uint32_t base4 = COEFF_OFFSET + 4 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base4 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base4 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base4 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[5]) {
                        const uint32_t base5 = COEFF_OFFSET + 5 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base5 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base5 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base5 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[6]) {
                        const uint32_t base6 = COEFF_OFFSET + 6 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base6 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base6 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base6 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[7]) {
                        const uint32_t base7 = COEFF_OFFSET + 7 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base7 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base7 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base7 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[8]) {
                        const uint32_t base8 = COEFF_OFFSET + 8 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base8 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base8 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base8 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[9]) {
                        const uint32_t base9 = COEFF_OFFSET + 9 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base9 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base9 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base9 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[10]) {
                        const uint32_t base10 = COEFF_OFFSET + 10 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base10 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base10 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base10 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[11]) {
                        const uint32_t base11 = COEFF_OFFSET + 11 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base11 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base11 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base11 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[12]) {
                        const uint32_t base12 = COEFF_OFFSET + 12 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base12 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base12 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base12 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[13]) {
                        const uint32_t base13 = COEFF_OFFSET + 13 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base13 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base13 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base13 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[14]) {
                        const uint32_t base14 = COEFF_OFFSET + 14 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base14 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base14 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base14 + b2_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[15]) {
                        const uint32_t base15 = COEFF_OFFSET + 15 * COEFFS_PER_SEGMENT;
                        if constexpr (b2_size >= 1) c[0] = lut[base15 + b2_start];
                        if constexpr (b2_size >= 2) c[1] = lut[base15 + b2_start + 1];
                        if constexpr (b2_size >= 3) c[2] = lut[base15 + b2_start + 2];
                    }
                    v_endif;

                    if constexpr (b2_size == 1) {
                        result = result * x + c[0];
                    } else if constexpr (b2_size == 2) {
                        result = (result * x + c[1]) * x + c[0];
                    } else {
                        result = ((result * x + c[2]) * x + c[1]) * x + c[0];
                    }
                }

                // Batch 3
                constexpr uint32_t remaining_after_b2 = (remaining_after_b1 > BATCH_SIZE) ? (remaining_after_b1 - BATCH_SIZE) : 0;
                if constexpr (remaining_after_b2 > 0) {
                    constexpr uint32_t b3_size = (remaining_after_b2 >= BATCH_SIZE) ? BATCH_SIZE : remaining_after_b2;
                    constexpr uint32_t b3_start = remaining_after_b2 - b3_size;

                    if constexpr (b3_size >= 1) c[0] = lut[base0 + b3_start];
                    if constexpr (b3_size >= 2) c[1] = lut[base0 + b3_start + 1];
                    if constexpr (b3_size >= 3) c[2] = lut[base0 + b3_start + 2];
                    v_if (x_clamped >= lut[1]) {
                        const uint32_t base1 = COEFF_OFFSET + 1 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base1 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base1 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base1 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[2]) {
                        const uint32_t base2 = COEFF_OFFSET + 2 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base2 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base2 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base2 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[3]) {
                        const uint32_t base3 = COEFF_OFFSET + 3 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base3 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base3 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base3 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[4]) {
                        const uint32_t base4 = COEFF_OFFSET + 4 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base4 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base4 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base4 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[5]) {
                        const uint32_t base5 = COEFF_OFFSET + 5 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base5 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base5 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base5 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[6]) {
                        const uint32_t base6 = COEFF_OFFSET + 6 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base6 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base6 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base6 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[7]) {
                        const uint32_t base7 = COEFF_OFFSET + 7 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base7 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base7 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base7 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[8]) {
                        const uint32_t base8 = COEFF_OFFSET + 8 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base8 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base8 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base8 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[9]) {
                        const uint32_t base9 = COEFF_OFFSET + 9 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base9 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base9 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base9 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[10]) {
                        const uint32_t base10 = COEFF_OFFSET + 10 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base10 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base10 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base10 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[11]) {
                        const uint32_t base11 = COEFF_OFFSET + 11 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base11 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base11 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base11 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[12]) {
                        const uint32_t base12 = COEFF_OFFSET + 12 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base12 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base12 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base12 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[13]) {
                        const uint32_t base13 = COEFF_OFFSET + 13 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base13 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base13 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base13 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[14]) {
                        const uint32_t base14 = COEFF_OFFSET + 14 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base14 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base14 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base14 + b3_start + 2];
                    }
                    v_endif;
                    v_if (x_clamped >= lut[15]) {
                        const uint32_t base15 = COEFF_OFFSET + 15 * COEFFS_PER_SEGMENT;
                        if constexpr (b3_size >= 1) c[0] = lut[base15 + b3_start];
                        if constexpr (b3_size >= 2) c[1] = lut[base15 + b3_start + 1];
                        if constexpr (b3_size >= 3) c[2] = lut[base15 + b3_start + 2];
                    }
                    v_endif;

                    if constexpr (b3_size == 1) {
                        result = result * x + c[0];
                    } else if constexpr (b3_size == 2) {
                        result = (result * x + c[1]) * x + c[0];
                    } else {
                        result = ((result * x + c[2]) * x + c[1]) * x + c[0];
                    }
                }
            }
        }

        dst_reg[d] = result;
    }
}


// Dispatcher that chooses between specialized and generic implementations
template <uint32_t POLY_DEGREE, uint32_t NUM_SEGMENTS, uint32_t LUT_SIZE>
inline void piecewise_generic_lut_opt_v2_dispatch(const std::array<float, LUT_SIZE>& lut) {
    if constexpr (NUM_SEGMENTS == 4) {
        piecewise_generic_lut_opt_v2_specialized_4<POLY_DEGREE, LUT_SIZE>(lut);
    } else if constexpr (NUM_SEGMENTS == 8) {
        piecewise_generic_lut_opt_v2_specialized_8<POLY_DEGREE, LUT_SIZE>(lut);
    } else if constexpr (NUM_SEGMENTS == 16) {
        piecewise_generic_lut_opt_v2_specialized_16<POLY_DEGREE, LUT_SIZE>(lut);
    } else {
        // Use generic implementation for other segment counts
        piecewise_generic_lut_opt_v2<POLY_DEGREE, NUM_SEGMENTS, LUT_SIZE>(lut);
    }
}

