#!/usr/bin/env python3
"""Deterministic SFPU-tutorial benchmark: a fixed odd-parity, mixed-degree
piecewise polynomial. No device, no external deps beyond numpy.

Emitted artifacts (consumed by the tutorial kernels + driver):
  kernels/common/bench_lut.h   - constexpr LUT in the production adhoc layout:
                                 [NUM_SEG+1 boundaries][seg0 c0..cMAX]...
  bench_reference.csv          - input,output (fp64 piecewise eval) for the
                                 correctness gate.

The polynomial is structured (odd parity + mixed per-segment degree) so that
every optimization in the ladder is both valid and exercised.
"""
import numpy as np
import os

SEED = 20260620
NUM_SEG = 16
MAX_DEG = 8
LO, HI = -8.0, 8.0


def build():
    rng = np.random.default_rng(SEED)
    bounds = np.linspace(LO, HI, NUM_SEG + 1)
    seg_deg = rng.choice([3, 5, 7, 8], size=NUM_SEG)  # mixed effective degree
    coeffs = np.zeros((NUM_SEG, MAX_DEG + 1))
    for s in range(NUM_SEG):
        for d in range(int(seg_deg[s]) + 1):
            if d % 2 == 0:
                continue  # odd parity: even coeffs = 0
            coeffs[s, d] = rng.uniform(-0.5, 0.5) / (d + 1)
    return bounds, seg_deg, coeffs


def lut_flat(bounds, coeffs):
    # production adhoc layout: boundaries block, then MAX_DEG+1 coeffs per segment
    flat = list(bounds)
    for s in range(NUM_SEG):
        flat += list(coeffs[s])
    return flat


def emit_header(path, bounds, seg_deg, coeffs):
    flat = lut_flat(bounds, coeffs)
    n = len(flat)
    with open(path, "w") as f:
        f.write("// GENERATED by gen_bench.py - do not edit\n#pragma once\n")
        f.write("#include <array>\n#include <cstdint>\n")
        f.write(f"constexpr uint32_t BENCH_NUM_SEGMENTS = {NUM_SEG};\n")
        f.write(f"constexpr uint32_t BENCH_MAX_DEGREE = {MAX_DEG};\n")
        f.write(f"constexpr float BENCH_RANGE_MIN = {LO}f;\n")
        f.write(f"constexpr float BENCH_RANGE_MAX = {HI}f;\n")
        f.write(f"constexpr uint32_t BENCH_LUT_SIZE = {n};\n")
        f.write(
            "constexpr uint32_t BENCH_SEGMENT_DEGREES[%d] = {%s};\n"
            % (NUM_SEG, ", ".join(str(int(d)) for d in seg_deg))
        )
        f.write("constexpr std::array<float, %d> BENCH_LUT = {{%s}};\n" % (n, ", ".join(f"{v:.9e}f" for v in flat)))


def emit_reference(path, bounds, coeffs):
    xs = np.linspace(LO, HI, 262144)
    out = np.empty_like(xs)
    for i, x in enumerate(xs):
        s = int(np.searchsorted(bounds, x, side="right") - 1)
        s = min(max(s, 0), NUM_SEG - 1)
        out[i] = sum(coeffs[s, d] * x**d for d in range(MAX_DEG + 1))
    np.savetxt(path, np.c_[xs, out], delimiter=",", header="input,output", comments="", fmt="%.9e")


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    b, sd, c = build()
    os.makedirs(os.path.join(here, "kernels/common"), exist_ok=True)
    emit_header(os.path.join(here, "kernels/common/bench_lut.h"), b, sd, c)
    emit_reference(os.path.join(here, "bench_reference.csv"), b, c)
    print(
        "wrote bench_lut.h + bench_reference.csv  (NUM_SEG=%d MAX_DEG=%d seg_deg=%s)"
        % (NUM_SEG, MAX_DEG, list(int(x) for x in sd))
    )
