#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

"""
Generate sweep_config.dat from tt-polynomial-fitter activations/*.json files.

This script reads all activation JSON files from tt-polynomial-fitter and generates
a unified sweep_config.dat file containing:
  - ACTIVATIONS: all available activations
  - NATIVE_SFPU_ACTIVATIONS: activations with native SFPU support
  - ACTIVATION_RANGES: per-activation test ranges

Usage:
  python3 generate_sweep_config.py
  python3 generate_sweep_config.py --activations-dir /path/to/activations
  python3 generate_sweep_config.py --output /path/to/sweep_config.dat

Environment:
  TT_POLY_FIT_DIR: Path to tt-polynomial-fitter repo (default: auto-detect)
"""

import argparse
import json
import os
from pathlib import Path
from typing import Dict, List


def find_activations_dir() -> Path:
    """Find the activations directory from tt-polynomial-fitter."""
    # Check environment variable
    if os.environ.get("TT_POLY_FIT_DIR"):
        base = Path(os.environ["TT_POLY_FIT_DIR"])
        if (base / "activations").exists():
            return base / "activations"

    # Try common paths
    candidates = [
        Path("/localdev/nkapre/tt-polynomial-fitter/activations"),
        Path.home() / "workspace/tt-polynomial-fitter/activations",
        Path("/Users/nkapre/workspace/tt-polynomial-fitter/activations"),
    ]

    for path in candidates:
        if path.exists():
            return path

    raise FileNotFoundError(
        "Could not find activations directory. Set TT_POLY_FIT_DIR or use --activations-dir"
    )


def load_activation_configs(activations_dir: Path) -> Dict[str, dict]:
    """Load all activation JSON configs."""
    configs = {}
    for json_file in sorted(activations_dir.glob("*.json")):
        try:
            with open(json_file) as f:
                config = json.load(f)
                name = config.get("name", json_file.stem)
                configs[name] = config
        except json.JSONDecodeError as e:
            print(f"Warning: Failed to parse {json_file}: {e}")
    return configs


def get_test_range(config: dict) -> tuple:
    """Get the test range for an activation.

    For activations with range reduction, use the original domain (not reduced).
    """
    domain = config.get("domain", {})
    return (
        domain.get("min", -10.0),
        domain.get("max", 10.0),
    )


def has_native_sfpu(config: dict) -> bool:
    """Check if activation has native SFPU support."""
    return config.get("has_native_sfpu", False)


def generate_sweep_config(
    configs: Dict[str, dict],
    output_path: Path,
    poly_degrees: List[int] = None,
    poly_segments: List[int] = None,
    poly_segmentations: List[str] = None,
    rational_degrees: List[int] = None,
    rational_segments: List[int] = None,
) -> None:
    """Generate sweep_config.dat from activation configs."""

    # Default configuration values (preserved from original)
    if poly_degrees is None:
        poly_degrees = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    if poly_segments is None:
        poly_segments = [2, 3, 4, 8, 16, 32, 64, 128]
    if poly_segmentations is None:
        poly_segmentations = ["uniform", "chebyshev", "curvature"]
    if rational_degrees is None:
        rational_degrees = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    if rational_segments is None:
        rational_segments = [1, 2, 5]

    # Sort activations alphabetically
    all_activations = sorted(configs.keys())
    native_sfpu_activations = sorted([
        name for name, cfg in configs.items() if has_native_sfpu(cfg)
    ])

    # Build ranges string
    ranges = []
    for name in sorted(configs.keys()):
        min_val, max_val = get_test_range(configs[name])
        ranges.append(f"{name}:{min_val}:{max_val}")

    content = f"""# =============================================================================
# Generic LUT Activation - Configuration
# =============================================================================
#
# AUTO-GENERATED by tools/generate_sweep_config.py
# DO NOT EDIT MANUALLY - regenerate using:
#   python3 tools/generate_sweep_config.py
#
# Single source of truth for:
# - generate_cmake_all.py (generates CMake targets)
# - generate_cmake_embedded.py (generates embedded CMake targets)
# - sweep_all.sh (polynomial sweep)
# - sweep_embedded.sh (embedded polynomial sweep)
# - sweep_rational.sh (rational sweep)
# - All other sweep scripts
#
# Format: Simple key=value pairs (bash-sourceable, Python-parseable)
# Arrays use comma-separated values
#
# =============================================================================

# =============================================================================
# ACTIVATIONS CONFIGURATION
# =============================================================================

# All activation functions to test (generated from {len(configs)} JSON files)
ACTIVATIONS={','.join(all_activations)}

# Activations with native SFPU support - includes composite ops for consistent naming (native_sfpu_ prefix)
NATIVE_SFPU_ACTIVATIONS={','.join(native_sfpu_activations)}

# Test ranges per activation (format: activation:min:max)
# Generated from activations/*.json domain fields
ACTIVATION_RANGES={','.join(ranges)}

# =============================================================================
# POLYNOMIAL CONFIGURATION
# =============================================================================

# Polynomial degrees to build and test
#POLY_DEGREES=1,2,3,4,6,7,8,12,14,16,12,16
POLY_DEGREES={','.join(str(d) for d in poly_degrees)}

# Segment counts for polynomials
POLY_SEGMENTS={','.join(str(s) for s in poly_segments)}

# Segmentation types
POLY_SEGMENTATIONS={','.join(poly_segmentations)}

# Precisions
POLY_PRECISIONS=bf16,fp32

# =============================================================================
# RATIONAL CONFIGURATION
# =============================================================================

# Rational degrees to build and test
# Will generate both (n,n) and (n+1,n) patterns
RATIONAL_DEGREES={','.join(str(d) for d in rational_degrees)}

# Segmentation types for rational approximations
RATIONAL_SEGMENTATIONS={','.join(poly_segmentations)}

# Segment counts for rational approximations
RATIONAL_SEGMENTS={','.join(str(s) for s in rational_segments)}

# =============================================================================
"""

    output_path.write_text(content)
    print(f"Generated: {output_path}")
    print(f"  Activations: {len(all_activations)}")
    print(f"  Native SFPU: {len(native_sfpu_activations)}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate sweep_config.dat from tt-polynomial-fitter activations",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--activations-dir",
        type=str,
        help="Path to activations/*.json directory",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        help="Output path for sweep_config.dat (default: auto-detect)",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Just list activations without generating",
    )

    args = parser.parse_args()

    # Find activations directory
    if args.activations_dir:
        activations_dir = Path(args.activations_dir)
    else:
        activations_dir = find_activations_dir()

    print(f"Loading activations from: {activations_dir}")
    configs = load_activation_configs(activations_dir)

    if not configs:
        print("Error: No activation configs found")
        return 1

    if args.list:
        print(f"\nFound {len(configs)} activations:")
        for name, cfg in sorted(configs.items()):
            min_val, max_val = get_test_range(cfg)
            native = "native" if has_native_sfpu(cfg) else ""
            rr = cfg.get("range_reduction", {}).get("method", "none")
            print(f"  {name:20s} [{min_val:8.3f}, {max_val:8.3f}] {native:6s} rr={rr}")
        return 0

    # Determine output path
    if args.output:
        output_path = Path(args.output)
    else:
        # Auto-detect: look for sweep_config.dat relative to this script
        script_dir = Path(__file__).parent.parent
        output_path = script_dir / "sweep_config.dat"

    generate_sweep_config(configs, output_path)
    return 0


if __name__ == "__main__":
    exit(main())
