#!/bin/bash
# register_new_sfpu.sh — Replace a composite op with a LUT-based SFPU kernel
#
# For activations that currently use a composite (multi-op chain) implementation,
# this script registers a new SFPU kernel and redirects the composite to use it.
#
# For activations that already have a native SFPU kernel, use apply_dropin.sh instead.
#
# Usage:
#   ./register_new_sfpu.sh --activation digamma \
#       --bf16-csv path/to/bf16.csv --fp32-csv path/to/fp32.csv
#
# What it does (minimal changes, proven on digamma):
#   NEW files (3):
#     - ckernel_sfpu_<name>.h (blackhole + wormhole, generated by generate_dropin_header.py)
#     - tt_metal/hw/inc/api/compute/eltwise_unary/<name>.h (API header)
#   MODIFIED files (5):
#     - unary_op_types.hpp: add DIGAMMA to UnaryOpType enum
#     - unary_op_utils.cpp: add macro mapping + tile dispatch (2 lines)
#     - sfpu_split_includes.h: add include guard (3 lines)
#     - unary.cpp: add template instantiation (1 line)
#     - unary_composite_op.cpp: replace multi-op chain with single SFPU call (1 line)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)

ACTIVATION=""
BF16_CSV=""
FP32_CSV=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --activation|-a) ACTIVATION="$2"; shift 2 ;;
        --bf16-csv)      BF16_CSV="$2"; shift 2 ;;
        --fp32-csv)      FP32_CSV="$2"; shift 2 ;;
        --dry-run)       DRY_RUN=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

[[ -z "$ACTIVATION" ]] && { echo "Error: --activation required"; exit 1; }
[[ -z "$BF16_CSV" ]] && { echo "Error: --bf16-csv required"; exit 1; }

NAME="$ACTIVATION"
NAME_UPPER=$(echo "$NAME" | tr '[:lower:]' '[:upper:]')
MACRO_NAME="SFPU_OP_${NAME_UPPER}_INCLUDE"
export TT_POLY_FIT_DIR="${TT_POLY_FIT_DIR:-/localdev/nkapre/tt-polynomial-fitter}"

BH_SFPU="$REPO_ROOT/tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_sfpu"
WH_SFPU="$REPO_ROOT/tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu"
API_DIR="$REPO_ROOT/tt_metal/hw/inc/api/compute/eltwise_unary"
UNARY_DIR="$REPO_ROOT/ttnn/cpp/ttnn/operations/eltwise/unary"

echo "================================================================"
echo "  Register New SFPU Kernel: $NAME"
echo "================================================================"

# Check if this is a composite op being replaced or a brand new op
COMPOSITE_CPP="$UNARY_DIR/device/unary_composite_op.cpp"
IS_COMPOSITE=false
if grep -q "_${NAME}\b" "$COMPOSITE_CPP" 2>/dev/null; then
    IS_COMPOSITE=true
    echo "  Detected: composite op (will replace multi-op chain with SFPU)"
else
    echo "  Detected: new op (no existing composite implementation)"
fi

echo ""
echo "Changes:"

# --- 1. Generate ckernel_sfpu_<name>.h ---
HEADER="ckernel_sfpu_${NAME}.h"
echo "  [NEW] $BH_SFPU/$HEADER"
echo "  [NEW] $WH_SFPU/$HEADER"

if [[ "$DRY_RUN" == false ]]; then
    GEN_ARGS="--activation $NAME --bf16-csv $BF16_CSV"
    [[ -n "$FP32_CSV" ]] && GEN_ARGS="$GEN_ARGS --fp32-csv $FP32_CSV"
    GEN_ARGS="$GEN_ARGS --output $BH_SFPU/$HEADER"
    python3 "$SCRIPT_DIR/generate_dropin_header.py" $GEN_ARGS
    cp "$BH_SFPU/$HEADER" "$WH_SFPU/$HEADER"
fi

# --- 2. Create API header (uses SFPU_UNARY_NO_PARAM_KERNEL_FN macro) ---
API_HEADER="$API_DIR/${NAME}.h"
echo "  [NEW] $API_HEADER"

if [[ "$DRY_RUN" == false ]]; then
    cat > "$API_HEADER" << APIEOF
// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "api/compute/common_globals.h"
#include "llk_math_eltwise_unary_sfpu_macros.h"
#ifdef TRISC_MATH
#include "ckernel_sfpu_${NAME}.h"
#endif

namespace ckernel {

ALWI void ${NAME}_tile(uint32_t idst) {
    MATH(SFPU_UNARY_NO_PARAM_KERNEL_FN(calculate_${NAME}, RC, APPROX, idst));
}

ALWI void ${NAME}_tile_init() { MATH(SFPU_UNARY_KERNEL_INIT(unused, APPROX)); }

}  // namespace ckernel
APIEOF
fi

# --- 3. Add to sfpu_split_includes.h ---
SPLIT_INCLUDES="$API_DIR/sfpu_split_includes.h"
echo "  [MOD] $SPLIT_INCLUDES"

if [[ "$DRY_RUN" == false ]]; then
    if ! grep -q "$MACRO_NAME" "$SPLIT_INCLUDES"; then
        # Insert before the SFPU_OP_COMPUTE_KERNEL_API_INCLUDE guard (always last)
        sed -i "/#if SFPU_OP_COMPUTE_KERNEL_API_INCLUDE/i\\#if ${MACRO_NAME}\n#include \"api/compute/eltwise_unary/${NAME}.h\"\n#endif\n" "$SPLIT_INCLUDES"
        echo "    Added $MACRO_NAME guard"
    else
        echo "    Already present"
    fi
fi

# --- 4. Add UnaryOpType enum value ---
OP_TYPES="$UNARY_DIR/common/unary_op_types.hpp"
echo "  [MOD] $OP_TYPES"

if [[ "$DRY_RUN" == false ]]; then
    if ! grep -q "    ${NAME_UPPER}," "$OP_TYPES"; then
        # Add after LGAMMA (last entry before closing brace of UnaryOpType enum)
        sed -i "/    LGAMMA,/a\\    ${NAME_UPPER}," "$OP_TYPES"
        echo "    Added ${NAME_UPPER} to UnaryOpType"
    else
        echo "    Already present"
    fi
fi

# --- 5. Add macro mapping + tile dispatch in unary_op_utils.cpp ---
OP_UTILS="$UNARY_DIR/common/unary_op_utils.cpp"
echo "  [MOD] $OP_UTILS"

if [[ "$DRY_RUN" == false ]]; then
    if ! grep -q "UnaryOpType::${NAME_UPPER}:" "$OP_UTILS"; then
        # Macro mapping: add before "default: return SFPU_OP_COMPUTE_KERNEL_API_INCLUDE"
        sed -i "/default: return \"SFPU_OP_COMPUTE_KERNEL_API_INCLUDE\"/i\\        case UnaryOpType::${NAME_UPPER}: return \"${MACRO_NAME}\";" "$OP_UTILS"
        echo "    Added macro mapping"

        # Tile dispatch: add before "default: TT_THROW" in get_op_init_and_func_default
        sed -i "/default: TT_THROW(\"Undefined non-parametrized op type/i\\        case UnaryOpType::${NAME_UPPER}: return {\"${NAME}_tile_init();\", fmt::format(\"${NAME}_tile({});\", idst)};" "$OP_UTILS"
        echo "    Added tile dispatch"
    else
        echo "    Already present"
    fi
fi

# --- 6. Add op definition in unary.cpp ---
# Current tree registers unary ops via the DEFINE_UNARY_OP(op_name, OP_TYPE) macro
# (the older `template struct ExecuteUnary<UnaryOpType::X>;` instantiation is gone).
UNARY_CPP="$UNARY_DIR/unary.cpp"
echo "  [MOD] $UNARY_CPP"

if [[ "$DRY_RUN" == false ]]; then
    if ! grep -q "DEFINE_UNARY_OP(${NAME}, ${NAME_UPPER})" "$UNARY_CPP"; then
        sed -i "/DEFINE_UNARY_OP(lgamma, LGAMMA)/a\\DEFINE_UNARY_OP(${NAME}, ${NAME_UPPER})" "$UNARY_CPP"
        echo "    Added DEFINE_UNARY_OP definition"
    else
        echo "    Already present"
    fi
fi

# --- 7. Replace composite implementation (if exists) ---
if [[ "$IS_COMPOSITE" == true ]]; then
    echo "  [MOD] $COMPOSITE_CPP (replacing composite chain with SFPU call)"

    if [[ "$DRY_RUN" == false ]]; then
        # Use Python to do the replacement safely (bash sed can't handle multi-line well)
        python3 -c "
import re
with open('$COMPOSITE_CPP') as f:
    content = f.read()

# Find the _${NAME} function and replace its body
pattern = r'(//[^\n]*\n)?Tensor _${NAME}\(const Tensor& input_a, const std::optional<MemoryConfig>& output_mem_config\) \{.*?\n\}'
replacement = '''// ${NAME}: LUT-based SFPU kernel (piecewise rational/polynomial)
Tensor _${NAME}(const Tensor& input_a, const std::optional<MemoryConfig>& output_mem_config) {
    return ttnn::operations::unary::ExecuteUnary<unary::UnaryOpType::${NAME_UPPER}>::invoke(input_a, output_mem_config);
}'''

new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)
if new_content != content:
    with open('$COMPOSITE_CPP', 'w') as f:
        f.write(new_content)
    print('    Replaced composite implementation')
else:
    print('    WARNING: Could not find _${NAME} function to replace')
"
    fi
fi

echo ""
echo "================================================================"
echo "  Done: $NAME"
echo "================================================================"
echo ""
echo "Next steps:"
echo "  1. Build: ./build_metal.sh"
echo "  2. Clear cache: rm -rf ~/.cache/tt-metal-cache"
echo "  3. Test: python3 -c \"import torch, ttnn; ...; ttnn.${NAME}(x)\""
echo ""
echo "To run full PR flow:"
echo "  ./tools/pr_submission.sh --activation $NAME"
