#!/bin/bash
# =============================================================================
# upload_pr_images.sh — Upload plot PNGs to nkapreTT/lut-pr-assets
#
# Uses the GitHub Contents API (no git clone needed). Returns markdown
# image URLs that render inline in PR descriptions.
#
# Usage:
#   ./upload_pr_images.sh --activation softplus --pr 39362 [--dir /path/to/plots]
#   ./upload_pr_images.sh --activation softplus --pr 39362 --file plot.png
#
# Returns one line per uploaded image:
#   ![filename](https://raw.githubusercontent.com/nkapreTT/lut-pr-assets/main/pr-39362/filename)
# =============================================================================
set -e

ASSETS_REPO="nkapreTT/lut-pr-assets"
ACTIVATION=""
PR_NUM=""
PLOT_DIR=""
SINGLE_FILE=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --activation|-a) ACTIVATION="$2"; shift 2 ;;
        --pr|-p)         PR_NUM="$2"; shift 2 ;;
        --dir|-d)        PLOT_DIR="$2"; shift 2 ;;
        --file|-f)       SINGLE_FILE="$2"; shift 2 ;;
        --dry-run)       DRY_RUN=true; shift ;;
        -h|--help)
            echo "Usage: $0 --activation <name> --pr <number> [--dir <path>] [--file <path>] [--dry-run]"
            echo ""
            echo "Uploads plot PNGs to $ASSETS_REPO and prints embeddable markdown URLs."
            echo "If --dir is given, uploads all *.png files in that directory."
            echo "If --file is given, uploads that single file."
            echo "If neither, auto-discovers plots for the activation."
            exit 0 ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

[[ -z "$ACTIVATION" ]] && { echo "Error: --activation required"; exit 1; }
[[ -z "$PR_NUM" ]] && { echo "Error: --pr required"; exit 1; }

REMOTE_PREFIX="pr-${PR_NUM}"
RAW_BASE="https://raw.githubusercontent.com/${ASSETS_REPO}/main/${REMOTE_PREFIX}"

# Collect files to upload
FILES=()
if [[ -n "$SINGLE_FILE" ]]; then
    FILES=("$SINGLE_FILE")
elif [[ -n "$PLOT_DIR" ]]; then
    while IFS= read -r f; do
        FILES+=("$f")
    done < <(find "$PLOT_DIR" -name "*.png" -maxdepth 2 2>/dev/null)
else
    # Auto-discover ULP distribution plots generated by pr_submission.sh step 3b.
    # These are the PRIMARY plots for PRs — ULP scatter distributions per precision.
    REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "/localdev/nkapre/tt-metal")
    EMB="$REPO_ROOT/tt_metal/programming_examples/generic_lut_activation_embedded"
    NON_EMB="$REPO_ROOT/tt_metal/programming_examples/generic_lut_activation"

    # 1. ULP distribution plots (generated by plot_hardware_error_analysis.py --standalone)
    #    Prefer ARCH_NAME arch, fall back to the other if no plots found.
    ARCH_SHORT="${ARCH_NAME:-wormhole_b0}"
    ARCH_SHORT="${ARCH_SHORT/_b0/}"
    ARCH_OTHER=$( [[ "$ARCH_SHORT" == "blackhole" ]] && echo "wormhole" || echo "blackhole" )
    for arch_dir in "$ARCH_SHORT" "$ARCH_OTHER"; do
        for base in \
            "$EMB/plots/${arch_dir}/hardware_error_analysis/${ACTIVATION}/ulp_only" \
            "$NON_EMB/plots/${arch_dir}/hardware_error_analysis/${ACTIVATION}/ulp_only"; do
            [[ -d "$base" ]] || continue
            for f in "$base"/*.png "$base"/combined/*.png; do
                [[ -f "$f" ]] && FILES+=("$f")
            done
        done
        [[ ${#FILES[@]} -gt 0 ]] && break
    done
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    echo "No plot files found for $ACTIVATION." >&2
    exit 0
fi

echo "Uploading ${#FILES[@]} plot(s) to ${ASSETS_REPO}/${REMOTE_PREFIX}/ ..." >&2

UPLOADED=0
for filepath in "${FILES[@]}"; do
    [[ ! -f "$filepath" ]] && continue
    fname=$(basename "$filepath")
    remote_path="${REMOTE_PREFIX}/${fname}"

    if [[ "$DRY_RUN" == true ]]; then
        echo "[DRY RUN] Would upload: $fname → $remote_path" >&2
        echo "![${fname}](${RAW_BASE}/${fname})"
        continue
    fi

    # Check if file already exists (avoid duplicate uploads)
    EXISTS=$(gh api "repos/${ASSETS_REPO}/contents/${remote_path}" --jq '.sha' 2>/dev/null || echo "")

    CONTENT=$(base64 -w0 "$filepath")
    PAYLOAD_FILE="/tmp/upload_payload_$$.json"

    # Build JSON payload using python to avoid printf issues with base64 % chars
    if [[ -n "$EXISTS" ]]; then
        python3 -c "
import json, sys
json.dump({'message': 'update $ACTIVATION plot: $fname', 'content': sys.stdin.read(), 'sha': '$EXISTS'}, open('$PAYLOAD_FILE','w'))
" <<< "$CONTENT"
    else
        python3 -c "
import json, sys
json.dump({'message': 'upload $ACTIVATION plot: $fname', 'content': sys.stdin.read().strip()}, open('$PAYLOAD_FILE','w'))
" <<< "$CONTENT"
    fi

    # Use --input to avoid argument-list-too-long for large base64 payloads.
    # Add a small delay between uploads to avoid GitHub API conflicts
    # (each upload creates a commit; rapid sequential uploads can conflict).
    sleep 1
    UPLOAD_RC=0
    gh api --method PUT \
        "repos/${ASSETS_REPO}/contents/${remote_path}" \
        --input "$PAYLOAD_FILE" \
        --jq '.content.html_url' >/dev/null 2>&1 || UPLOAD_RC=$?

    if [[ $UPLOAD_RC -ne 0 ]]; then
        # May be a conflict (file exists with stale sha). Re-fetch and retry.
        sleep 1
        EXISTS=$(gh api "repos/${ASSETS_REPO}/contents/${remote_path}" --jq '.sha' 2>/dev/null || echo "")
        if [[ -n "$EXISTS" ]]; then
            python3 -c "
import json, sys
json.dump({'message': 'update $ACTIVATION plot: $fname', 'content': sys.stdin.read().strip(), 'sha': '$EXISTS'}, open('$PAYLOAD_FILE','w'))
" <<< "$CONTENT"
            gh api --method PUT \
                "repos/${ASSETS_REPO}/contents/${remote_path}" \
                --input "$PAYLOAD_FILE" \
                --jq '.content.html_url' >/dev/null 2>&1 && UPLOAD_RC=0 || UPLOAD_RC=1
        fi
    fi
    rm -f "$PAYLOAD_FILE"

    if [[ $UPLOAD_RC -eq 0 ]]; then
        UPLOADED=$((UPLOADED + 1))
        echo "![${fname}](${RAW_BASE}/${fname})"
        echo "  ✓ ${fname}" >&2
    else
        echo "  ✗ ${fname} (upload failed)" >&2
    fi
done

echo "" >&2
echo "Uploaded $UPLOADED/${#FILES[@]} files to ${ASSETS_REPO}/${REMOTE_PREFIX}/" >&2
